x-consumer-raw-defaults: &consumer-raw-template
  build:
    context: .
    dockerfile: Dockerfile.consumer-raw
  volumes:
    - ./:/app/consumer-raw
    - ../data_lake:/app/data_lake
    - ../log:/app/log
  command: ["/app/consumer-raw/entrypoint_raw.sh"]
  networks:
    - streaming_default
  restart: always  # <= Ajout ici

services:

  consumer-raw-1:
    <<: *consumer-raw-template
    container_name: consumer-raw-1
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: transaction_log
      SCHEMA: "False"
      WRITE_MODE: append

  consumer-raw-2:
    <<: *consumer-raw-template
    container_name: consumer-raw-2
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_PROCESSING
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-3:
    <<: *consumer-raw-template
    container_name: consumer-raw-3
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_PENDING
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-4:
    <<: *consumer-raw-template
    container_name: consumer-raw-4
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_IMPORTANTES_700
      SCHEMA: "True"
      WRITE_MODE: append


  consumer-raw-5:
    <<: *consumer-raw-template
    container_name: consumer-raw-5
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_FAILED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-6:
    <<: *consumer-raw-template
    container_name: consumer-raw-6
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_CONVERTED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-7:
    <<: *consumer-raw-template
    container_name: consumer-raw-7
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_CONVERTED_CLEANED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-8:
    <<: *consumer-raw-template
    container_name: consumer-raw-8
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_COMPLETED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-9:
    <<: *consumer-raw-template
    container_name: consumer-raw-9
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_CANCELLED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-10:
    <<: *consumer-raw-template
    container_name: consumer-raw-10
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: TRANSACTIONS_BLACKLIST
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-11:
    <<: *consumer-raw-template
    container_name: consumer-raw-11
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: ALL_TRANSACTIONS_FLATTENED
      SCHEMA: "True"
      WRITE_MODE: append

  consumer-raw-13:
    <<: *consumer-raw-template
    container_name: consumer-raw-13
    environment:
      PY_FILE: write_stream_to_parquet.py
      KAFKA_TOPIC: ALL_TRANSACTIONS_ANONYMIZED
      SCHEMA: "True"
      WRITE_MODE: append

networks:
  streaming_default:
    external: true
