x-writer-table-defaults: &writer-table-template
  build:
    context: .
    dockerfile: Dockerfile.writer-table
  volumes:
    - ./:/app/writer-table
    - ../data_lake:/app/data_lake
    - ../log:/app/log
  command: ["/app/writer-table/entrypoint_table.sh"]
  networks:
    - streaming_default
  restart: always  # <= Ajout ici

services:
  writer-table-1:
    <<: *writer-table-template
    container_name: writer-table-1
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: AMOUNT_PER_TYPE_WINDOWED

  writer-table-2:
    <<: *writer-table-template
    container_name: writer-table-2
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: writer_COUNT_NUMB_BUY_PER_PRODUCT

  writer-table-3:
    <<: *writer-table-template
    container_name: writer-table-3
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: TOTAL_PAR_TRANSACTION_TYPE
  
  writer-table-4:
    <<: *writer-table-template
    container_name: writer-table-4
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: TOTAL_SPENT_PER_USER_TRANSACTION_TYPE

  writer-table-5:
    <<: *writer-table-template
    container_name: writer-table-5
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: TOTAL_TRANSACTION_AMOUNT_PER_PAYMENT_METHOD

  writer-table-6:
    <<: *writer-table-template
    container_name: writer-table-6
    environment:
      PY_FILE: write_table_to_postgres.py
      KAFKA_TOPIC: TRANSACTION_STATUS_EVOLUTION

networks:
  streaming_default:
    external: true
